### ISSUE TITLE
Items not showing up in search or discover.

### ISSUE THREAD

**Issue by ohhdemgirls** [nbdy/dhtc#1]
While the landing page states `Collected info hashes: 57162` neither `/discover` or `/search` show any items.

**Comment by nbdy** [comment]
I'm kinda baffled you were able to collect >50k info hashes with this.
This project isn't being used by me anymore.
You might want to have a look at [dhtgo](https://github.com/nbdy/dhtgo).
It's also still work in progress, but fetches metadata way faster.

I will archive this repository soon. Sorry for the inconvenience.

**Comment by nbdy** [comment]
Closing this issue and archiving this repository since [dhtgo](https://github.com/nbdy/dhtgo) now provides all the functionality this project should have had.
