### ISSUE TITLE
Filter Illegal Torrents

### ISSUE THREAD

**Issue by trentwiles** [nbdy/dhtc#1]
I'd like to run this software, but I don't want child porn indexed. Can you add a few keywords to filter this kind of content?

**Comment by nbdy** [comment]
I'm currently quiet busy with moving and work. Internet at my new place is an issue too, so I'm sorry for not responding as fast as I could.

I imagine we could have a text file containing a bunch of undesired keywords, which will be translated into a list at start of the program.
That way it should be possible to hook a function into [insertMetadata](https://github.com/nbdy/dhtc/blob/34bb99a55e4585acf40f15c3b4aeee94cd9fb3b6/main.go#L217) and check the name of the torrent or even the files for all the keywords.

As soon as the Telekom gets it's ass up I can get back to testing and implement something like that if that sounds good to you.

**Comment by nbdy** [comment]
I've added a blacklist feature.
You can add new entries via the web ui or per batch with the parameters "-nameBlacklist" and "-fileBlacklist".
If you want to enable the feature you have to pass -enableBlacklist.

If you want to have keywords added, please fork, edit the name-blacklist.txt or file-blacklist.txt files and open a pull request.

**Comment by trentwiles** [comment]
Thank you!
