### ISSUE TITLE
Windows version not working from exe

### ISSUE THREAD

**Issue by pactwothousand** [nbdy/dhtc#5]
Tried executing the exe, it runs (can see it briefly in task manager) then disappears.

**Comment by nbdy** [comment]
Did you run it via the command line or just double-clicked it?

**Comment by nbdy** [comment]
I've created [v1.0.1](https://github.com/nbdy/dhtc/releases/tag/v1.0.1) which will automatically create the database directory and has the default bootstrap nodes hard-coded so one does not have to create the bootstrap-nodes.txt.

Please reopen if you face any other issues.
