### ISSUE TITLE
DBG Protocol error received: 'invalid node ID' (203)

### ISSUE THREAD

**Issue by pactwothousand** [nbdy/dhtc#6]
Version 1.01 works for a short while, and I can access localhost:4200 but then starts producing this error. 

DBG Protocol error received: 'invalid node ID' (203)
![DHTC](https://github.com/nbdy/dhtc/assets/127617212/a41c6274-b394-4884-bf3d-339d8857a4d4)
 
And the internet is disconnected, and restores as soon as dhtc-windows.exe is closed.

**Comment by nbdy** [comment]
I'm not able to reproduce the issue of internet disconnecting with a Windows 10 VM.

I was able to reproduce the protocol errors and the eventual slowing down of incoming info hashes on Windows.
It also seems to be rather resource intensive on Windows (70-100% CPU usage), which I have not experienced with Linux.

I also get protocol errors when running in a docker container, but certainly not that frequently.

Until I find time to analyze this I'd recommend using it with docker.

**Comment by pactwothousand** [comment]
It's working in a clean VM.


Thanks for your help.
